package com.hlv.HalvaBot.Model;

public enum UserState {
    DEFAULT,
    AWAITING_NAME,
    AWAITING_PHONE,
    AWAITING_WORKPLACE,
    AWAITING_POSITION,
    AWAITING_MARITAL_STATUS,
    AWAITING_INCOME,
    AWAITING_CREDIT_LIMIT,
    AWAITING_NAME_REFINANCE,
    AWAITING_PHONE_REFINANCE,
    AWAITING_ACCOUNT_NUMBERS,
    AWAITING_REFINANCE_AMOUNT,
    AWAITING_DOCUMENT,
    AWAITING_PAYMENT_AMOUNT,
    AWAITING_PAYMENT_MONTHS,
    AWAITING_PAYMENT_SUBSCRIPTION,
    AWAITING_PAYMENT_SUPER_OPTION,
    AWAITING_PAYMENT_CARD_TYPE

}
